In [2]:
import numpy as np 
import pandas as pd

In [3]:
data = {
    "name" : ["daksh","raj","mahir"],
    "age" : [21,22,21]
}

In [8]:
df = pd.DataFrame(data)

In [11]:
df = pd.read_csv("")
df = pd.read_xlsx("")
df = pd.read_json("")
df = pd.read_sql(query,connection)

    name  age
0  daksh   21
1    raj   22
2  mahir   21

In [ ]:
df.head()
df.head(10)
df.tail()
df.shape
df.info()
df.describe()

df['age']
df[['age','name']]

#iloc is position based -> it uses index like arrays df.iloc[10]
#loc is names bases or label based df.loc[:,"age"] can use index also but iloc cant use names or labels

In [ ]:
df.isnull()
df.dropna()
df.dropna(axis = 1) #axis = 1 -> columns axis = 0 -> rows
df.fillna(0)
df['Marks'].fillna(df['Marks'].mean())
df['age'] = df['age'].astype(float) #type converstion

df.replace(1,"one")

df.rename(columns = {"old_name" : "new_name"}
df.set_index("name")

df[df["age"] >30]
df[(df["age"] > 30) & (df["marks"] > 80)]

In [ ]:
df.sort_values("age")
df.sort_values("age",ascending = False)

In [27]:
data = {
    "Department": ["IT", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 40000, 45000]
}

df = pd.DataFrame(data)
df.groupby("Department")["Salary"].mean()
df

  Department  Salary
0         IT   50000
1         IT   60000
2         HR   40000
3         HR   45000

In [24]:
np.mean(df['Salary'])

df.apply(np.mean) # applies to all the columns
df.apply(np..max, axis = 1) # row wise - axis = 1

np.float64(48750.0)

In [26]:
#pivot table
df.pivot_table(
    index = "Department",
    values = "Salary",
    aggfunc = np.mean
)

C:\Users\daksh\AppData\Local\Temp\ipykernel_33516\4031001211.py:2: FutureWarning: The provided callable <function mean at 0x0000000009267240> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.pivot_table(

             Salary
Department
HR          42500.0
IT          55000.0

In [ ]:
df1.append(df2) #adds rows - appending data
#or 
pd.concat([df1,df2])
pd.concat([df1,df2], axis = 1)

df1.join(df2, how ="inner") #inner left right outer

df.mean()
df.max()
df.min()
df.meadian()
df.std() 
df.corr()